In [1]:
import sqlite3
import pandas as pd
import numpy as np

%matplotlib inline
import matplotlib.pyplot as plt

In [2]:
db_path = "../data/database.sqlite"

conn = sqlite3.connect(db_path)
cur = conn.cursor()

In [3]:
cur.execute("SELECT name FROM sqlite_master WHERE type='table';")
cur.fetchall()

[('sqlite_sequence',),
 ('Player_Attributes',),
 ('Player',),
 ('Match',),
 ('League',),
 ('Country',),
 ('Team',),
 ('Team_Attributes',)]

In [4]:
matches_df = pd.read_sql_query("SELECT * FROM %s" % "Match", conn)

In [5]:
matches_df.head()

id  country_id  league_id     season  stage                 date  \
0   1           1          1  2008/2009      1  2008-08-17 00:00:00   
1   2           1          1  2008/2009      1  2008-08-16 00:00:00   
2   3           1          1  2008/2009      1  2008-08-16 00:00:00   
3   4           1          1  2008/2009      1  2008-08-17 00:00:00   
4   5           1          1  2008/2009      1  2008-08-16 00:00:00   

   match_api_id  home_team_api_id  away_team_api_id  home_team_goal  ...   \
0        492473              9987              9993               1  ...    
1        492474             10000              9994               0  ...    
2        492475              9984              8635               0  ...    
3        492476              9991              9998               5  ...    
4        492477              7947              9985               1  ...    

    SJA   VCH   VCD   VCA   GBH   GBD   GBA   BSH   BSD   BSA  
0  4.00  1.65  3.40  4.50  1.78  3.25  4.00  1.73  3.40  4.20  
1  3.80  2.00  3.25  3.25  1.85  3.25  3.75  1.91  3.25  3.60  
2  2.50  2.35  3.25  2.65  2.50  3.20  2.50  2.30  3.20  2.75  
3  7.50  1.45  3.75  6.50  1.50  3.75  5.50  1.44  3.75  6.50  
4  1.73  4.50  3.40  1.65  4.50  3.50  1.65  4.75  3.30  1.67  

[5 rows x 115 columns]

In [26]:
matches_df.shape

(25979, 115)

In [95]:
player_df = pd.read_sql_query("SELECT * FROM %s" % "Player", conn)

player_df.shape

(11060, 7)

In [17]:
ht_x_pos_cols = [
"home_player_X1",
"home_player_X2",
"home_player_X3",
"home_player_X4",
"home_player_X5",
"home_player_X6",
"home_player_X7",
"home_player_X8",
"home_player_X9",
"home_player_X10",
"home_player_X11"
]

ht_y_pos_cols = [
"home_player_Y1",
"home_player_Y2",
"home_player_Y3",
"home_player_Y4",
"home_player_Y5",
"home_player_Y6",
"home_player_Y7",
"home_player_Y8",
"home_player_Y9",
"home_player_Y10",
"home_player_Y11"
]


at_x_pos = [
"away_player_X1",
"away_player_X2",
"away_player_X3",
"away_player_X4",
"away_player_X5",
"away_player_X6",
"away_player_X7",
"away_player_X8",
"away_player_X9",
"away_player_X10",
"away_player_X11"
]

at_y_pos = [
"away_player_Y1",
"away_player_Y2",
"away_player_Y3",
"away_player_Y4",
"away_player_Y5",
"away_player_Y6",
"away_player_Y7",
"away_player_Y8",
"away_player_Y9",
"away_player_Y10",
"away_player_Y11"
]


In [73]:
positions = matches_df.loc[:, ht_x_pos + ht_y_pos + at_x_pos + at_y_pos]

def extract_team_positions(match):
    home_team_pos = {}
    away_team_pos = {}
    
    for i in range(1, 12):
        key = "player{}".format(i)
        
        strx = "home_player_X{}".format(i)
        stry = "home_player_Y{}".format(i)
        x, y = match[strx], match[stry]
        home_team_pos[key] = (x, y)
        
        strx = "away_player_X{}".format(i)
        stry = "away_player_Y{}".format(i)
        x, y = match[strx], match[stry]
        away_team_pos[key] = (x, y)
        
    return away_team_pos, home_team_pos

def plot_pos(pos_dict):
    xs = []
    ys = []
    
    for k, (x, y) in pos_dict.items():
        xs.append(x)
        ys.append(y)
    
    plt.scatter(xs, ys)



atpos, htpos = extract_team_positions(positions.iloc[25768])

print(atpos)
print(htpos)




{'player1': (1.0, 1.0), 'player2': (8.0, 3.0), 'player3': (6.0, 3.0), 'player4': (4.0, 3.0), 'player5': (2.0, 3.0), 'player6': (5.0, 8.0), 'player7': (3.0, 8.0), 'player8': (6.0, 6.0), 'player9': (4.0, 6.0), 'player10': (7.0, 8.0), 'player11': (5.0, 11.0)}
{'player1': (1.0, 1.0), 'player2': (2.0, 3.0), 'player3': (4.0, 3.0), 'player4': (6.0, 3.0), 'player5': (8.0, 3.0), 'player6': (5.0, 6.0), 'player7': (2.0, 8.0), 'player8': (4.0, 8.0), 'player9': (6.0, 8.0), 'player10': (8.0, 8.0), 'player11': (5.0, 11.0)}


In [84]:
matches_df.iloc[25768]["away_player_1"]

67311.0

In [96]:
player_df[player_df.player_api_id == 67311]

id  player_api_id       player_name  player_fifa_api_id  \
4042  4046          67311  Guillaume Faivre              170785   

                 birthday  height  weight  
4042  1987-02-20 00:00:00  187.96     183

In [79]:

def get_field(pos):
    field = np.zeros(shape=(9, 11))
    
    for k, (x, y) in pos.items():
        i = int(x) - 1
        j = int(y) - 1
        field[i, j] = 1
        
    return field
        
field = get_field(atpos)
print(field)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


## Note:
This weird position (0,0) corresponds to player *Guillaume_Faivre* the __goal keeper__!


This explains how we should read the positions: __from left to right__ i.e. this team has 4 defenders and 1 forward striker ...

In [97]:
field = get_field(htpos)

print(field)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


maybe we should exclude goal keepers alltogether as their influence on the positioning game is rather static and finding *a good position* for the goal keeper here is not really trivial ...

In [70]:
positions.max()

home_player_X1      2.0
home_player_X2      8.0
home_player_X3      8.0
home_player_X4      8.0
home_player_X5      9.0
home_player_X6      9.0
home_player_X7      9.0
home_player_X8      9.0
home_player_X9      9.0
home_player_X10     9.0
home_player_X11     7.0
home_player_Y1      3.0
home_player_Y2      3.0
home_player_Y3      5.0
home_player_Y4      5.0
home_player_Y5      8.0
home_player_Y6      9.0
home_player_Y7      9.0
home_player_Y8     10.0
home_player_Y9     10.0
home_player_Y10    11.0
home_player_Y11    11.0
away_player_X1      6.0
away_player_X2      8.0
away_player_X3      9.0
away_player_X4      8.0
away_player_X5      9.0
away_player_X6      9.0
away_player_X7      9.0
away_player_X8      9.0
away_player_X9      9.0
away_player_X10     9.0
away_player_X11     8.0
away_player_Y1      3.0
away_player_Y2      3.0
away_player_Y3      7.0
away_player_Y4      7.0
away_player_Y5      9.0
away_player_Y6     10.0
away_player_Y7     10.0
away_player_Y8     10.0
away_player_Y9  

not all matches have positioning data ... about 1840 rows are missing

In [103]:
positions.isna().sum()

home_player_X1     1821
home_player_X2     1821
home_player_X3     1832
home_player_X4     1832
home_player_X5     1832
home_player_X6     1832
home_player_X7     1832
home_player_X8     1832
home_player_X9     1832
home_player_X10    1832
home_player_X11    1832
home_player_Y1     1821
home_player_Y2     1821
home_player_Y3     1832
home_player_Y4     1832
home_player_Y5     1832
home_player_Y6     1832
home_player_Y7     1832
home_player_Y8     1832
home_player_Y9     1832
home_player_Y10    1832
home_player_Y11    1832
away_player_X1     1832
away_player_X2     1832
away_player_X3     1832
away_player_X4     1832
away_player_X5     1832
away_player_X6     1832
away_player_X7     1832
away_player_X8     1832
away_player_X9     1833
away_player_X10    1833
away_player_X11    1839
away_player_Y1     1832
away_player_Y2     1832
away_player_Y3     1832
away_player_Y4     1832
away_player_Y5     1832
away_player_Y6     1832
away_player_Y7     1832
away_player_Y8     1832
away_player_Y9  

of about 25979 rows

In [104]:
positions.shape

(25979, 44)